# If you would like to crawl DocsPen contact us at support@docspen.com.

User-agent: Googlebot
Allow: /
Allow: /@/*
Allow: /books/*
Allow: /books/*/page/*
Allow: /books/*/chapter/*/*
Disallow: /books/*/edit
Disallow: /books/*/page/*/edit
Disallow: /books/*/chapter/*/*/edit
Disallow: /books/*/draft/*
Disallow: /books/*/sort
Disallow: /books/*/permissions
Disallow: /books/*/delete
Disallow: /books/*/draft/*/delete
Disallow: /books/*/chapter/*/*/edit
Disallow: /books/*/page/create
Disallow: /books/*/chapter/create
Disallow: /books/create
Disallow: /books/*/export/html
Disallow: /books/*/export/pdf
Disallow: /books/*/export/plaintext
Disallow: /books/*/*/*/export/html
Disallow: /books/*/*/*/export/pdf
Disallow: /books/*/*/*/export/plaintext
Disallow: /books/*/*/*//export/html
Disallow: /books/*/chapter/*/export/pdf
Disallow: /books/*/chapter/*/export/plaintext
Disallow: /search
Disallow: /settings
Disallow: /git
Disallow: /trello
Disallow: /slack
Disallow: /logout
Disallow: /login

User-agent: duckduckbot
Allow: /
Allow: /@/*
Allow: /books/*
Allow: /books/*/page/*
Allow: /books/*/chapter/*/*
Disallow: /books/*/edit
Disallow: /books/*/page/*/edit
Disallow: /books/*/chapter/*/*/edit
Disallow: /books/*/draft/*
Disallow: /books/*/sort
Disallow: /books/*/permissions
Disallow: /books/*/delete
Disallow: /books/*/draft/*/delete
Disallow: /books/*/chapter/*/*/edit
Disallow: /books/*/page/create
Disallow: /books/*/chapter/create
Disallow: /books/create
Disallow: /books/*/export/html
Disallow: /books/*/export/pdf
Disallow: /books/*/export/plaintext
Disallow: /books/*/*/*/export/html
Disallow: /books/*/*/*/export/pdf
Disallow: /books/*/*/*/export/plaintext
Disallow: /books/*/*/*//export/html
Disallow: /books/*/chapter/*/export/pdf
Disallow: /books/*/chapter/*/export/plaintext
Disallow: /search
Disallow: /settings
Disallow: /git
Disallow: /trello
Disallow: /slack
Disallow: /logout
Disallow: /login

User-agent: Bingbot
Allow: /
Allow: /@/*
Allow: /books/*
Allow: /books/*/page/*
Allow: /books/*/chapter/*/*
Disallow: /books/*/edit
Disallow: /books/*/page/*/edit
Disallow: /books/*/chapter/*/*/edit
Disallow: /books/*/draft/*
Disallow: /books/*/sort
Disallow: /books/*/permissions
Disallow: /books/*/delete
Disallow: /books/*/draft/*/delete
Disallow: /books/*/chapter/*/*/edit
Disallow: /books/*/page/create
Disallow: /books/*/chapter/create
Disallow: /books/create
Disallow: /books/*/export/html
Disallow: /books/*/export/pdf
Disallow: /books/*/export/plaintext
Disallow: /books/*/*/*/export/html
Disallow: /books/*/*/*/export/pdf
Disallow: /books/*/*/*/export/plaintext
Disallow: /books/*/*/*//export/html
Disallow: /books/*/chapter/*/export/pdf
Disallow: /books/*/chapter/*/export/plaintext
Disallow: /search
Disallow: /settings
Disallow: /git
Disallow: /trello
Disallow: /slack
Disallow: /logout
Disallow: /login

User-agent: ia_archiver
Allow: /
Allow: /@/*
Allow: /books/*
Allow: /books/*/page/*
Allow: /books/*/chapter/*/*
Disallow: /books/*/edit
Disallow: /books/*/page/*/edit
Disallow: /books/*/chapter/*/*/edit
Disallow: /books/*/draft/*
Disallow: /books/*/sort
Disallow: /books/*/permissions
Disallow: /books/*/delete
Disallow: /books/*/draft/*/delete
Disallow: /books/*/chapter/*/*/edit
Disallow: /books/*/page/create
Disallow: /books/*/chapter/create
Disallow: /books/create
Disallow: /books/*/export/html
Disallow: /books/*/export/pdf
Disallow: /books/*/export/plaintext
Disallow: /books/*/*/*/export/html
Disallow: /books/*/*/*/export/pdf
Disallow: /books/*/*/*/export/plaintext
Disallow: /books/*/*/*//export/html
Disallow: /books/*/chapter/*/export/pdf
Disallow: /books/*/chapter/*/export/plaintext
Disallow: /search
Disallow: /settings
Disallow: /git
Disallow: /trello
Disallow: /slack
Disallow: /logout
Disallow: /login

User-agent: CCBot
Allow: /
Allow: /@/*
Allow: /books/*
Allow: /books/*/page/*
Allow: /books/*/chapter/*/*
Disallow: /books/*/edit
Disallow: /books/*/page/*/edit
Disallow: /books/*/chapter/*/*/edit
Disallow: /books/*/draft/*
Disallow: /books/*/sort
Disallow: /books/*/permissions
Disallow: /books/*/delete
Disallow: /books/*/draft/*/delete
Disallow: /books/*/chapter/*/*/edit
Disallow: /books/*/page/create
Disallow: /books/*/chapter/create
Disallow: /books/create
Disallow: /books/*/export/html
Disallow: /books/*/export/pdf
Disallow: /books/*/export/plaintext
Disallow: /books/*/*/*/export/html
Disallow: /books/*/*/*/export/pdf
Disallow: /books/*/*/*/export/plaintext
Disallow: /books/*/*/*//export/html
Disallow: /books/*/chapter/*/export/pdf
Disallow: /books/*/chapter/*/export/plaintext
Disallow: /search
Disallow: /settings
Disallow: /git
Disallow: /trello
Disallow: /slack
Disallow: /logout
Disallow: /login

User-agent: coccoc
Allow: /
Allow: /@/*
Allow: /books/*
Allow: /books/*/page/*
Allow: /books/*/chapter/*/*
Disallow: /books/*/edit
Disallow: /books/*/page/*/edit
Disallow: /books/*/chapter/*/*/edit
Disallow: /books/*/draft/*
Disallow: /books/*/sort
Disallow: /books/*/permissions
Disallow: /books/*/delete
Disallow: /books/*/draft/*/delete
Disallow: /books/*/chapter/*/*/edit
Disallow: /books/*/page/create
Disallow: /books/*/chapter/create
Disallow: /books/create
Disallow: /books/*/export/html
Disallow: /books/*/export/pdf
Disallow: /books/*/export/plaintext
Disallow: /books/*/*/*/export/html
Disallow: /books/*/*/*/export/pdf
Disallow: /books/*/*/*/export/plaintext
Disallow: /books/*/*/*//export/html
Disallow: /books/*/chapter/*/export/pdf
Disallow: /books/*/chapter/*/export/plaintext
Disallow: /search
Disallow: /settings
Disallow: /git
Disallow: /trello
Disallow: /slack
Disallow: /logout
Disallow: /login

User-agent: Daumoa
Allow: /
Allow: /@/*
Allow: /books/*
Allow: /books/*/page/*
Allow: /books/*/chapter/*/*
Disallow: /books/*/edit
Disallow: /books/*/page/*/edit
Disallow: /books/*/chapter/*/*/edit
Disallow: /books/*/draft/*
Disallow: /books/*/sort
Disallow: /books/*/permissions
Disallow: /books/*/delete
Disallow: /books/*/draft/*/delete
Disallow: /books/*/chapter/*/*/edit
Disallow: /books/*/page/create
Disallow: /books/*/chapter/create
Disallow: /books/create
Disallow: /books/*/export/html
Disallow: /books/*/export/pdf
Disallow: /books/*/export/plaintext
Disallow: /books/*/*/*/export/html
Disallow: /books/*/*/*/export/pdf
Disallow: /books/*/*/*/export/plaintext
Disallow: /books/*/*/*//export/html
Disallow: /books/*/chapter/*/export/pdf
Disallow: /books/*/chapter/*/export/plaintext
Disallow: /search
Disallow: /settings
Disallow: /git
Disallow: /trello
Disallow: /slack
Disallow: /logout
Disallow: /login

User-agent: dotbot
Allow: /
Allow: /@/*
Allow: /books/*
Allow: /books/*/page/*
Allow: /books/*/chapter/*/*
Disallow: /books/*/edit
Disallow: /books/*/page/*/edit
Disallow: /books/*/chapter/*/*/edit
Disallow: /books/*/draft/*
Disallow: /books/*/sort
Disallow: /books/*/permissions
Disallow: /books/*/delete
Disallow: /books/*/draft/*/delete
Disallow: /books/*/chapter/*/*/edit
Disallow: /books/*/page/create
Disallow: /books/*/chapter/create
Disallow: /books/create
Disallow: /books/*/export/html
Disallow: /books/*/export/pdf
Disallow: /books/*/export/plaintext
Disallow: /books/*/*/*/export/html
Disallow: /books/*/*/*/export/pdf
Disallow: /books/*/*/*/export/plaintext
Disallow: /books/*/*/*//export/html
Disallow: /books/*/chapter/*/export/pdf
Disallow: /books/*/chapter/*/export/plaintext
Disallow: /search
Disallow: /settings
Disallow: /git
Disallow: /trello
Disallow: /slack
Disallow: /logout
Disallow: /login

User-agent: EtaoSpider
Allow: /
Allow: /@/*
Allow: /books/*
Allow: /books/*/page/*
Allow: /books/*/chapter/*/*
Disallow: /books/*/edit
Disallow: /books/*/page/*/edit
Disallow: /books/*/chapter/*/*/edit
Disallow: /books/*/draft/*
Disallow: /books/*/sort
Disallow: /books/*/permissions
Disallow: /books/*/delete
Disallow: /books/*/draft/*/delete
Disallow: /books/*/chapter/*/*/edit
Disallow: /books/*/page/create
Disallow: /books/*/chapter/create
Disallow: /books/create
Disallow: /books/*/export/html
Disallow: /books/*/export/pdf
Disallow: /books/*/export/plaintext
Disallow: /books/*/*/*/export/html
Disallow: /books/*/*/*/export/pdf
Disallow: /books/*/*/*/export/plaintext
Disallow: /books/*/*/*//export/html
Disallow: /books/*/chapter/*/export/pdf
Disallow: /books/*/chapter/*/export/plaintext
Disallow: /search
Disallow: /settings
Disallow: /git
Disallow: /trello
Disallow: /slack
Disallow: /logout
Disallow: /login

User-agent: HTTrack
Allow: /
Allow: /@/*
Allow: /books/*
Allow: /books/*/page/*
Allow: /books/*/chapter/*/*
Disallow: /books/*/edit
Disallow: /books/*/page/*/edit
Disallow: /books/*/chapter/*/*/edit
Disallow: /books/*/draft/*
Disallow: /books/*/sort
Disallow: /books/*/permissions
Disallow: /books/*/delete
Disallow: /books/*/draft/*/delete
Disallow: /books/*/chapter/*/*/edit
Disallow: /books/*/page/create
Disallow: /books/*/chapter/create
Disallow: /books/create
Disallow: /books/*/export/html
Disallow: /books/*/export/pdf
Disallow: /books/*/export/plaintext
Disallow: /books/*/*/*/export/html
Disallow: /books/*/*/*/export/pdf
Disallow: /books/*/*/*/export/plaintext
Disallow: /books/*/*/*//export/html
Disallow: /books/*/chapter/*/export/pdf
Disallow: /books/*/chapter/*/export/plaintext
Disallow: /search
Disallow: /settings
Disallow: /git
Disallow: /trello
Disallow: /slack
Disallow: /logout
Disallow: /login

User-agent: IntuitGSACrawler
Allow: /
Allow: /@/*
Allow: /books/*
Allow: /books/*/page/*
Allow: /books/*/chapter/*/*
Disallow: /books/*/edit
Disallow: /books/*/page/*/edit
Disallow: /books/*/chapter/*/*/edit
Disallow: /books/*/draft/*
Disallow: /books/*/sort
Disallow: /books/*/permissions
Disallow: /books/*/delete
Disallow: /books/*/draft/*/delete
Disallow: /books/*/chapter/*/*/edit
Disallow: /books/*/page/create
Disallow: /books/*/chapter/create
Disallow: /books/create
Disallow: /books/*/export/html
Disallow: /books/*/export/pdf
Disallow: /books/*/export/plaintext
Disallow: /books/*/*/*/export/html
Disallow: /books/*/*/*/export/pdf
Disallow: /books/*/*/*/export/plaintext
Disallow: /books/*/*/*//export/html
Disallow: /books/*/chapter/*/export/pdf
Disallow: /books/*/chapter/*/export/plaintext
Disallow: /search
Disallow: /settings
Disallow: /git
Disallow: /trello
Disallow: /slack
Disallow: /logout
Disallow: /login

User-agent: Mail.RU_Bot
Allow: /
Allow: /@/*
Allow: /books/*
Allow: /books/*/page/*
Allow: /books/*/chapter/*/*
Disallow: /books/*/edit
Disallow: /books/*/page/*/edit
Disallow: /books/*/chapter/*/*/edit
Disallow: /books/*/draft/*
Disallow: /books/*/sort
Disallow: /books/*/permissions
Disallow: /books/*/delete
Disallow: /books/*/draft/*/delete
Disallow: /books/*/chapter/*/*/edit
Disallow: /books/*/page/create
Disallow: /books/*/chapter/create
Disallow: /books/create
Disallow: /books/*/export/html
Disallow: /books/*/export/pdf
Disallow: /books/*/export/plaintext
Disallow: /books/*/*/*/export/html
Disallow: /books/*/*/*/export/pdf
Disallow: /books/*/*/*/export/plaintext
Disallow: /books/*/*/*//export/html
Disallow: /books/*/chapter/*/export/pdf
Disallow: /books/*/chapter/*/export/plaintext
Disallow: /search
Disallow: /settings
Disallow: /git
Disallow: /trello
Disallow: /slack
Disallow: /logout
Disallow: /login

User-agent: msnbot
Allow: /
Allow: /@/*
Allow: /books/*
Allow: /books/*/page/*
Allow: /books/*/chapter/*/*
Disallow: /books/*/edit
Disallow: /books/*/page/*/edit
Disallow: /books/*/chapter/*/*/edit
Disallow: /books/*/draft/*
Disallow: /books/*/sort
Disallow: /books/*/permissions
Disallow: /books/*/delete
Disallow: /books/*/draft/*/delete
Disallow: /books/*/chapter/*/*/edit
Disallow: /books/*/page/create
Disallow: /books/*/chapter/create
Disallow: /books/create
Disallow: /books/*/export/html
Disallow: /books/*/export/pdf
Disallow: /books/*/export/plaintext
Disallow: /books/*/*/*/export/html
Disallow: /books/*/*/*/export/pdf
Disallow: /books/*/*/*/export/plaintext
Disallow: /books/*/*/*//export/html
Disallow: /books/*/chapter/*/export/pdf
Disallow: /books/*/chapter/*/export/plaintext
Disallow: /search
Disallow: /settings
Disallow: /git
Disallow: /trello
Disallow: /slack
Disallow: /logout
Disallow: /login

User-agent: naverbot
Allow: /
Allow: /@/*
Allow: /books/*
Allow: /books/*/page/*
Allow: /books/*/chapter/*/*
Disallow: /books/*/edit
Disallow: /books/*/page/*/edit
Disallow: /books/*/chapter/*/*/edit
Disallow: /books/*/draft/*
Disallow: /books/*/sort
Disallow: /books/*/permissions
Disallow: /books/*/delete
Disallow: /books/*/draft/*/delete
Disallow: /books/*/chapter/*/*/edit
Disallow: /books/*/page/create
Disallow: /books/*/chapter/create
Disallow: /books/create
Disallow: /books/*/export/html
Disallow: /books/*/export/pdf
Disallow: /books/*/export/plaintext
Disallow: /books/*/*/*/export/html
Disallow: /books/*/*/*/export/pdf
Disallow: /books/*/*/*/export/plaintext
Disallow: /books/*/*/*//export/html
Disallow: /books/*/chapter/*/export/pdf
Disallow: /books/*/chapter/*/export/plaintext
Disallow: /search
Disallow: /settings
Disallow: /git
Disallow: /trello
Disallow: /slack
Disallow: /logout
Disallow: /login

User-agent: red-app-gsa-p-one
Allow: /
Allow: /@/*
Allow: /books/*
Allow: /books/*/page/*
Allow: /books/*/chapter/*/*
Disallow: /books/*/edit
Disallow: /books/*/page/*/edit
Disallow: /books/*/chapter/*/*/edit
Disallow: /books/*/draft/*
Disallow: /books/*/sort
Disallow: /books/*/permissions
Disallow: /books/*/delete
Disallow: /books/*/draft/*/delete
Disallow: /books/*/chapter/*/*/edit
Disallow: /books/*/page/create
Disallow: /books/*/chapter/create
Disallow: /books/create
Disallow: /books/*/export/html
Disallow: /books/*/export/pdf
Disallow: /books/*/export/plaintext
Disallow: /books/*/*/*/export/html
Disallow: /books/*/*/*/export/pdf
Disallow: /books/*/*/*/export/plaintext
Disallow: /books/*/*/*//export/html
Disallow: /books/*/chapter/*/export/pdf
Disallow: /books/*/chapter/*/export/plaintext
Disallow: /search
Disallow: /settings
Disallow: /git
Disallow: /trello
Disallow: /slack
Disallow: /logout
Disallow: /login

User-agent: rogerbot
Allow: /
Allow: /@/*
Allow: /books/*
Allow: /books/*/page/*
Allow: /books/*/chapter/*/*
Disallow: /books/*/edit
Disallow: /books/*/page/*/edit
Disallow: /books/*/chapter/*/*/edit
Disallow: /books/*/draft/*
Disallow: /books/*/sort
Disallow: /books/*/permissions
Disallow: /books/*/delete
Disallow: /books/*/draft/*/delete
Disallow: /books/*/chapter/*/*/edit
Disallow: /books/*/page/create
Disallow: /books/*/chapter/create
Disallow: /books/create
Disallow: /books/*/export/html
Disallow: /books/*/export/pdf
Disallow: /books/*/export/plaintext
Disallow: /books/*/*/*/export/html
Disallow: /books/*/*/*/export/pdf
Disallow: /books/*/*/*/export/plaintext
Disallow: /books/*/*/*//export/html
Disallow: /books/*/chapter/*/export/pdf
Disallow: /books/*/chapter/*/export/plaintext
Disallow: /search
Disallow: /settings
Disallow: /git
Disallow: /trello
Disallow: /slack
Disallow: /logout
Disallow: /login

User-agent: SandDollar
Allow: /
Allow: /@/*
Allow: /books/*
Allow: /books/*/page/*
Allow: /books/*/chapter/*/*
Disallow: /books/*/edit
Disallow: /books/*/page/*/edit
Disallow: /books/*/chapter/*/*/edit
Disallow: /books/*/draft/*
Disallow: /books/*/sort
Disallow: /books/*/permissions
Disallow: /books/*/delete
Disallow: /books/*/draft/*/delete
Disallow: /books/*/chapter/*/*/edit
Disallow: /books/*/page/create
Disallow: /books/*/chapter/create
Disallow: /books/create
Disallow: /books/*/export/html
Disallow: /books/*/export/pdf
Disallow: /books/*/export/plaintext
Disallow: /books/*/*/*/export/html
Disallow: /books/*/*/*/export/pdf
Disallow: /books/*/*/*/export/plaintext
Disallow: /books/*/*/*//export/html
Disallow: /books/*/chapter/*/export/pdf
Disallow: /books/*/chapter/*/export/plaintext
Disallow: /search
Disallow: /settings
Disallow: /git
Disallow: /trello
Disallow: /slack
Disallow: /logout
Disallow: /login

User-agent: seznambot
Allow: /
Allow: /@/*
Allow: /books/*
Allow: /books/*/page/*
Allow: /books/*/chapter/*/*
Disallow: /books/*/edit
Disallow: /books/*/page/*/edit
Disallow: /books/*/chapter/*/*/edit
Disallow: /books/*/draft/*
Disallow: /books/*/sort
Disallow: /books/*/permissions
Disallow: /books/*/delete
Disallow: /books/*/draft/*/delete
Disallow: /books/*/chapter/*/*/edit
Disallow: /books/*/page/create
Disallow: /books/*/chapter/create
Disallow: /books/create
Disallow: /books/*/export/html
Disallow: /books/*/export/pdf
Disallow: /books/*/export/plaintext
Disallow: /books/*/*/*/export/html
Disallow: /books/*/*/*/export/pdf
Disallow: /books/*/*/*/export/plaintext
Disallow: /books/*/*/*//export/html
Disallow: /books/*/chapter/*/export/pdf
Disallow: /books/*/chapter/*/export/plaintext
Disallow: /search
Disallow: /settings
Disallow: /git
Disallow: /trello
Disallow: /slack
Disallow: /logout
Disallow: /login

User-agent: Slurp
Allow: /
Allow: /@/*
Allow: /books/*
Allow: /books/*/page/*
Allow: /books/*/chapter/*/*
Disallow: /books/*/edit
Disallow: /books/*/page/*/edit
Disallow: /books/*/chapter/*/*/edit
Disallow: /books/*/draft/*
Disallow: /books/*/sort
Disallow: /books/*/permissions
Disallow: /books/*/delete
Disallow: /books/*/draft/*/delete
Disallow: /books/*/chapter/*/*/edit
Disallow: /books/*/page/create
Disallow: /books/*/chapter/create
Disallow: /books/create
Disallow: /books/*/export/html
Disallow: /books/*/export/pdf
Disallow: /books/*/export/plaintext
Disallow: /books/*/*/*/export/html
Disallow: /books/*/*/*/export/pdf
Disallow: /books/*/*/*/export/plaintext
Disallow: /books/*/*/*//export/html
Disallow: /books/*/chapter/*/export/pdf
Disallow: /books/*/chapter/*/export/plaintext
Disallow: /search
Disallow: /settings
Disallow: /git
Disallow: /trello
Disallow: /slack
Disallow: /logout
Disallow: /login

User-agent: Swiftbot
Allow: /
Allow: /@/*
Allow: /books/*
Allow: /books/*/page/*
Allow: /books/*/chapter/*/*
Disallow: /books/*/edit
Disallow: /books/*/page/*/edit
Disallow: /books/*/chapter/*/*/edit
Disallow: /books/*/draft/*
Disallow: /books/*/sort
Disallow: /books/*/permissions
Disallow: /books/*/delete
Disallow: /books/*/draft/*/delete
Disallow: /books/*/chapter/*/*/edit
Disallow: /books/*/page/create
Disallow: /books/*/chapter/create
Disallow: /books/create
Disallow: /books/*/export/html
Disallow: /books/*/export/pdf
Disallow: /books/*/export/plaintext
Disallow: /books/*/*/*/export/html
Disallow: /books/*/*/*/export/pdf
Disallow: /books/*/*/*/export/plaintext
Disallow: /books/*/*/*//export/html
Disallow: /books/*/chapter/*/export/pdf
Disallow: /books/*/chapter/*/export/plaintext
Disallow: /search
Disallow: /settings
Disallow: /git
Disallow: /trello
Disallow: /slack
Disallow: /logout
Disallow: /login

User-agent: Telefonica
Allow: /
Allow: /@/*
Allow: /books/*
Allow: /books/*/page/*
Allow: /books/*/chapter/*/*
Disallow: /books/*/edit
Disallow: /books/*/page/*/edit
Disallow: /books/*/chapter/*/*/edit
Disallow: /books/*/draft/*
Disallow: /books/*/sort
Disallow: /books/*/permissions
Disallow: /books/*/delete
Disallow: /books/*/draft/*/delete
Disallow: /books/*/chapter/*/*/edit
Disallow: /books/*/page/create
Disallow: /books/*/chapter/create
Disallow: /books/create
Disallow: /books/*/export/html
Disallow: /books/*/export/pdf
Disallow: /books/*/export/plaintext
Disallow: /books/*/*/*/export/html
Disallow: /books/*/*/*/export/pdf
Disallow: /books/*/*/*/export/plaintext
Disallow: /books/*/*/*//export/html
Disallow: /books/*/chapter/*/export/pdf
Disallow: /books/*/chapter/*/export/plaintext
Disallow: /search
Disallow: /settings
Disallow: /git
Disallow: /trello
Disallow: /slack
Disallow: /logout
Disallow: /login

User-agent: teoma
Allow: /
Allow: /@/*
Allow: /books/*
Allow: /books/*/page/*
Allow: /books/*/chapter/*/*
Disallow: /books/*/edit
Disallow: /books/*/page/*/edit
Disallow: /books/*/chapter/*/*/edit
Disallow: /books/*/draft/*
Disallow: /books/*/sort
Disallow: /books/*/permissions
Disallow: /books/*/delete
Disallow: /books/*/draft/*/delete
Disallow: /books/*/chapter/*/*/edit
Disallow: /books/*/page/create
Disallow: /books/*/chapter/create
Disallow: /books/create
Disallow: /books/*/export/html
Disallow: /books/*/export/pdf
Disallow: /books/*/export/plaintext
Disallow: /books/*/*/*/export/html
Disallow: /books/*/*/*/export/pdf
Disallow: /books/*/*/*/export/plaintext
Disallow: /books/*/*/*//export/html
Disallow: /books/*/chapter/*/export/pdf
Disallow: /books/*/chapter/*/export/plaintext
Disallow: /search
Disallow: /settings
Disallow: /git
Disallow: /trello
Disallow: /slack
Disallow: /logout
Disallow: /login

User-agent: Twitterbot
Allow: /
Allow: /@/*
Allow: /books/*
Allow: /books/*/page/*
Allow: /books/*/chapter/*/*
Disallow: /books/*/edit
Disallow: /books/*/page/*/edit
Disallow: /books/*/chapter/*/*/edit
Disallow: /books/*/draft/*
Disallow: /books/*/sort
Disallow: /books/*/permissions
Disallow: /books/*/delete
Disallow: /books/*/draft/*/delete
Disallow: /books/*/chapter/*/*/edit
Disallow: /books/*/page/create
Disallow: /books/*/chapter/create
Disallow: /books/create
Disallow: /books/*/export/html
Disallow: /books/*/export/pdf
Disallow: /books/*/export/plaintext
Disallow: /books/*/*/*/export/html
Disallow: /books/*/*/*/export/pdf
Disallow: /books/*/*/*/export/plaintext
Disallow: /books/*/*/*//export/html
Disallow: /books/*/chapter/*/export/pdf
Disallow: /books/*/chapter/*/export/plaintext
Disallow: /search
Disallow: /settings
Disallow: /git
Disallow: /trello
Disallow: /slack
Disallow: /logout
Disallow: /login

User-agent: Yandex
Allow: /
Allow: /@/*
Allow: /books/*
Allow: /books/*/page/*
Allow: /books/*/chapter/*/*
Disallow: /books/*/edit
Disallow: /books/*/page/*/edit
Disallow: /books/*/chapter/*/*/edit
Disallow: /books/*/draft/*
Disallow: /books/*/sort
Disallow: /books/*/permissions
Disallow: /books/*/delete
Disallow: /books/*/draft/*/delete
Disallow: /books/*/chapter/*/*/edit
Disallow: /books/*/page/create
Disallow: /books/*/chapter/create
Disallow: /books/create
Disallow: /books/*/export/html
Disallow: /books/*/export/pdf
Disallow: /books/*/export/plaintext
Disallow: /books/*/*/*/export/html
Disallow: /books/*/*/*/export/pdf
Disallow: /books/*/*/*/export/plaintext
Disallow: /books/*/*/*//export/html
Disallow: /books/*/chapter/*/export/pdf
Disallow: /books/*/chapter/*/export/plaintext
Disallow: /search
Disallow: /settings
Disallow: /git
Disallow: /trello
Disallow: /slack
Disallow: /logout
Disallow: /login

User-agent: *
Allow: /humans.txt
Disallow: /

# Some bots are known to be trouble, particularly those designed to copy
# entire sites. Please obey robots.txt.
User-agent: sitecheck.internetseer.com
Disallow: /

User-agent: Zealbot
Disallow: /



# Misbehaving: requests much too fast:
User-agent: fast
Disallow: /

#
# Sorry, wget in its recursive mode is a frequent problem.
# Please read the man page and use it properly; there is a
# --wait option you can use to set the delay between hits,
# for instance.
#
User-agent: wget
Disallow: /

Sitemap: https://docspen.ga/sitemap.xml